VIRTUAL_WIDTH = 640
VIRTUAL_HEIGHT = 368

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 736

TILE_SIZE = 16

-- player jumping velocity
PLAYER_JUMP_VELOCITY = -350
PLAYER_RUN_SPEED = 150
PLAYER_WALK_SPEED = 100
PLAYER_DASH_DIST = TILE_SIZE * 6

FLAME_MOVE_SPEED = 100 * 60
FLAME_SINE_SPEED = 5
FLAME_TARGET_Y_FROM_PLAYER = TILE_SIZE*1.5
FLAME_TARGET_X_FROM_PLAYER = TILE_SIZE/2

CAMERA_ZOOM = 2

GRAVITY = 1000

ENEMY_CHASE_MIN_DISTANCE = TILE_SIZE * 5
ENEMY_ATTACK_COOL_DOWN_TIME = 2


-- DEBUG constants

USE_ZOOM = true

PLAYER_CATEGORY = 2
FLAME_CATEGORY = 3
ARCHER_BANDIT_CATEGORY = 4
DAGGER_BANDIT_CATEGORY = 5
SPITTER_CATEGORY = 6
GHOUL_CATEGORY = 7
BOSS_CATEGORY = 8

TORCH_CATEGORY = 9